/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PluginsRouteImport } from './routes/plugins'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as DocsDotmdRouteImport } from './routes/docs[.]md'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PluginsPluginIdRouteImport } from './routes/plugins_.$pluginId'
import { Route as DownloadMacosRouteImport } from './routes/download.macos'
import { Route as DocsChar123Char125DotmdRouteImport } from './routes/docs/{$}[.]md'
import { Route as DocsLlmsDottxtRouteImport } from './routes/docs/llms[.]txt'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as ApiSearchRouteImport } from './routes/api/search'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsRoute = PluginsRouteImport.update({
  id: '/plugins',
  path: '/plugins',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsDotmdRoute = DocsDotmdRouteImport.update({
  id: '/docs.md',
  path: '/docs.md',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsPluginIdRoute = PluginsPluginIdRouteImport.update({
  id: '/plugins_/$pluginId',
  path: '/plugins/$pluginId',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadMacosRoute = DownloadMacosRouteImport.update({
  id: '/download/macos',
  path: '/download/macos',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsChar123Char125DotmdRoute = DocsChar123Char125DotmdRouteImport.update({
  id: '/docs/{$}.md',
  path: '/docs/{$}.md',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsLlmsDottxtRoute = DocsLlmsDottxtRouteImport.update({
  id: '/docs/llms.txt',
  path: '/docs/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/docs.md': typeof DocsDotmdRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/plugins': typeof PluginsRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/llms.txt': typeof DocsLlmsDottxtRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/download/macos': typeof DownloadMacosRoute
  '/plugins/$pluginId': typeof PluginsPluginIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs.md': typeof DocsDotmdRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/plugins': typeof PluginsRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/llms.txt': typeof DocsLlmsDottxtRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/download/macos': typeof DownloadMacosRoute
  '/plugins/$pluginId': typeof PluginsPluginIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/docs.md': typeof DocsDotmdRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/plugins': typeof PluginsRoute
  '/privacy': typeof PrivacyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/api/search': typeof ApiSearchRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/llms.txt': typeof DocsLlmsDottxtRoute
  '/docs/{$}.md': typeof DocsChar123Char125DotmdRoute
  '/download/macos': typeof DownloadMacosRoute
  '/plugins_/$pluginId': typeof PluginsPluginIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/docs.md'
    | '/llms.txt'
    | '/plugins'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/api/search'
    | '/docs/$'
    | '/docs/llms.txt'
    | '/docs/{$}.md'
    | '/download/macos'
    | '/plugins/$pluginId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs.md'
    | '/llms.txt'
    | '/plugins'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/api/search'
    | '/docs/$'
    | '/docs/llms.txt'
    | '/docs/{$}.md'
    | '/download/macos'
    | '/plugins/$pluginId'
  id:
    | '__root__'
    | '/'
    | '/docs.md'
    | '/llms.txt'
    | '/plugins'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/api/search'
    | '/docs/$'
    | '/docs/llms.txt'
    | '/docs/{$}.md'
    | '/download/macos'
    | '/plugins_/$pluginId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocsDotmdRoute: typeof DocsDotmdRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  PluginsRoute: typeof PluginsRoute
  PrivacyRoute: typeof PrivacyRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  ApiSearchRoute: typeof ApiSearchRoute
  DocsSplatRoute: typeof DocsSplatRoute
  DocsLlmsDottxtRoute: typeof DocsLlmsDottxtRoute
  DocsChar123Char125DotmdRoute: typeof DocsChar123Char125DotmdRoute
  DownloadMacosRoute: typeof DownloadMacosRoute
  PluginsPluginIdRoute: typeof PluginsPluginIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins': {
      id: '/plugins'
      path: '/plugins'
      fullPath: '/plugins'
      preLoaderRoute: typeof PluginsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs.md': {
      id: '/docs.md'
      path: '/docs.md'
      fullPath: '/docs.md'
      preLoaderRoute: typeof DocsDotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins_/$pluginId': {
      id: '/plugins_/$pluginId'
      path: '/plugins/$pluginId'
      fullPath: '/plugins/$pluginId'
      preLoaderRoute: typeof PluginsPluginIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/macos': {
      id: '/download/macos'
      path: '/download/macos'
      fullPath: '/download/macos'
      preLoaderRoute: typeof DownloadMacosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/{$}.md': {
      id: '/docs/{$}.md'
      path: '/docs/{$}.md'
      fullPath: '/docs/{$}.md'
      preLoaderRoute: typeof DocsChar123Char125DotmdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/llms.txt': {
      id: '/docs/llms.txt'
      path: '/docs/llms.txt'
      fullPath: '/docs/llms.txt'
      preLoaderRoute: typeof DocsLlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocsDotmdRoute: DocsDotmdRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  PluginsRoute: PluginsRoute,
  PrivacyRoute: PrivacyRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  ApiSearchRoute: ApiSearchRoute,
  DocsSplatRoute: DocsSplatRoute,
  DocsLlmsDottxtRoute: DocsLlmsDottxtRoute,
  DocsChar123Char125DotmdRoute: DocsChar123Char125DotmdRoute,
  DownloadMacosRoute: DownloadMacosRoute,
  PluginsPluginIdRoute: PluginsPluginIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
