import CodevisorCore
import CodevisorUI
import SwiftUI
import UIKit

// MARK: - Workspace screen

/// A workspace: one full-screen pane (tab) at a time — chats, terminals, and
/// the new-tab page. Tabs are switched from the sidebar, which lists every
/// pane; the nav bar shows the active pane's title between the system back
/// button and a new-tab button. Chats also show their workspace and machine
/// in the native navigation subtitle.
struct WorkspaceScreen: View {
  @Environment(AppEnvironment.self) var environment
  @Environment(\.dismiss) var dismiss
  @Environment(\.accessibilityReduceMotion) var accessibilityReduceMotion
  /// Stack (compact, native back) or split detail (iPhone Duo unfolded).
  @Environment(\.homeLayoutMode) var homeLayoutMode
  /// A tiled split sidebar already names this screen.
  @Environment(\.homeSidebarIsTiled) var homeSidebarIsTiled
  /// iPhone Duo moved the bar items into its side strip.
  @Environment(\.workspaceBarsAreVertical) var barsAreVertical
  /// The workspace's chat, or nil while the native New Chat sheet owns the
  /// draft composer. Its first send adopts a real session in place; Home then
  /// mounts an ordinary workspace route backed by the same cached controller
  /// before removing the opaque sheet.
  let sessionId: UUID?
  /// Machine identity is part of a session's key. The same server database
  /// can be visible through both a direct/local registration and Codevisor
  /// Cloud, so UUID alone is intentionally insufficient for lookups.
  var serverId: String? = nil
  /// Stable workspace identity for normal routes. Agent rows also supply a
  /// preferred chat; workspace rows leave it nil so the last-open tab wins.
  var workspaceId: UUID? = nil
  var preferredChatSessionId: UUID? = nil
  /// A sidebar tab row names the exact pane to show (a terminal, browser,
  /// plugin, or New Tab page) instead of the workspace's last selection.
  var preferredPaneId: UUID? = nil
  /// The split leaf holding that pane, activated on a regular-width layout.
  var preferredLeafId: UUID? = nil
  /// Reports the pane this screen actually shows whenever it changes, so a
  /// split layout's route can follow the workspace's own moves — New Tab, a
  /// conversion, a close, an agent navigating — instead of keeping the pane
  /// a sidebar tap last asked for.
  var onSelectedPaneChanged: ((WorkspacePaneSelection) -> Void)? = nil
  /// Existing workspaces receive their cached-or-new controller from Home
  /// during destination construction, so the transcript shell is available
  /// on the first frame instead of waiting for this view's async task.
  var initialController: SessionController? = nil
  /// New Chat is hosted by a real system sheet. This flag changes only the
  /// navigation controls; presentation chrome remains system-owned.
  var isNewChatPresentation = false
  var isPromotingNewChat = false
  var promotionNavigationTitle: WorkspaceNavigationTitle? = nil
  /// A one-shot request created when Home begins presenting New Chat. It is
  /// carried to the UIKit editor without being regenerated by view updates.
  var initialComposerFocusRequest: UUID? = nil
  /// Clears the request at its source after UIKit accepts it. Keeping this
  /// acknowledgement above the destination means even an unexpected
  /// composer remount cannot focus the keyboard a second time.
  var onInitialComposerFocusRequestFulfilled: ((UUID) -> Void)? = nil
  /// The first send has minted a real session. HomeView mounts an ordinary
  /// workspace route beneath the sheet.
  /// A first send is about to create its session and workspace. Home
  /// starts the sheet's expansion here, BEFORE those publications dirty
  /// the whole Home hierarchy, so the expansion's commit is cheap.
  var onDraftWillStart: (() -> Void)? = nil
  var onDraftStarted: ((UUID) -> Void)? = nil
  /// The no-project browser pushes into the sheet's type-erased path. Once a
  /// folder is selected, Home removes only those browser entries.
  /// Home owns the native sheet's Boolean presentation state, so the close
  /// button requests dismissal there. Normal workspace routes keep using
  /// the environment dismiss action.
  var onDismissNewChat: (() -> Void)? = nil
  /// A normal workspace destination reports when its cached transcript has
  /// mounted. Home uses this to remove the opaque sheet without exposing a
  /// spinner or an intermediate navigation frame.
  var onWorkspaceReady: ((UUID) -> Void)? = nil
  /// A destination mounted beneath a promoted New Chat may prepare its
  /// transcript, but the still-visible sheet remains the presentation and
  /// scroll owner until Home commits the handoff.
  var transcriptPresentationRole: TranscriptPresentationRole = .foreground
  var onSendAnimationCompleted: ((UserSendAnimationRequest) -> Void)? = nil
  var onSendAnimationStarted:
    (
      (
        UserSendAnimationRequest,
        TranscriptSendAnimationTarget
      ) -> Bool
    )? = nil
  var onComposerWillSend: ((String, CGRect) -> Void)? = nil
  var composerTextEditorHandoffRole: ComposerTextEditorHandoffRole = .none
  var composerTextEditorHandoffID: UUID? = nil

  /// One controller per chat session shown in this workspace (macOS allows
  /// several chats per workspace; so do we).
  @State var controllers: [UUID: SessionController] = [:]
  @State var missing = false
  @State var serverConfig: CodevisorServerConfig?
  @State var project: Project?
  @State var paneState: PaneGroupState?
  /// Set when a draft's first send creates its session. From then on this
  /// screen is that workspace — same view, same pane, same transcript.
  @State var startedSessionId: UUID?
  /// The retained draft controller while `sessionId` is nil.
  @State var draftController: SessionController?
  /// SwiftUI identity for pane content, keyed by pane id. When workspace
  /// sync replaces a local pane with the server's record of the same
  /// resource (a first chat's pane takes the session's id), the new id
  /// inherits the old identity so the mounted transcript is not rebuilt.
  @State var paneViewIdentities: [UUID: UUID] = [:]
  /// The draft's first send landed: the run pickers collapse away.
  @State var hasStarted = false
  /// Stands in for the session id a draft doesn't have yet, so its pane
  /// group can exist (and keep a STABLE pane id) from the first frame.
  @State var draftPlaceholderId = UUID()

  /// This workspace's chat: the routed one, or the one a draft's first send
  /// created. Nil only while an unsent draft.
  var activeSessionId: UUID? { sessionId ?? startedSessionId }

  var isDraft: Bool { activeSessionId == nil && workspaceId == nil }

  /// The first send is under way the moment its optimistic message exists —
  /// before the scratch folder or session is created. The run pickers
  /// collapse on that, not on adoption, so the composer responds to the tap
  /// rather than to the network.
  var presentsAsStarted: Bool {
    isPromotingNewChat || hasStarted || (isDraft && draftController?.pendingUserMessage != nil)
  }

  var resolvedServerId: String {
    serverId ?? draftController?.project.serverId ?? environment.defaultComposerServerId
  }

  var resolvedWorkspace: Workspace? {
    if let workspaceId,
      let workspace = environment.workspaces.loadAll().first(where: {
        $0.serverId == resolvedServerId && $0.id == workspaceId
      })
    {
      return workspace
    }
    guard let activeSessionId else { return nil }
    return environment.workspaces.loadAll().first {
      $0.serverId == resolvedServerId && $0.chatSessionIds.contains(activeSessionId)
    }
  }

  var panes: PaneGroupState {
    if let paneState { return paneState }
    if let workspace = resolvedWorkspace {
      return Self.compactPaneState(from: workspace)
    }
    if let paneStorageId {
      return WorkspacePaneStore.shared.state(
        for: paneStorageId,
        legacySessionIds: legacyPaneSessionIds
      )
    }
    // A draft's pane exists before its session does, keyed by a
    // placeholder so its id — and therefore the chat view's identity —
    // survives the session being adopted.
    return PaneGroupState.centerInitial(sessionId: draftPlaceholderId)
  }

  var activePane: PaneDescriptorState? {
    panes.selectedPane ?? panes.panes.first
  }

  func session(for id: UUID) -> ChatSession? {
    environment.projectList.sessions.first {
      $0.serverId == resolvedServerId && $0.id == id
    }
  }

  var rootSession: ChatSession? { activeSessionId.flatMap(session(for:)) }

  /// The persisted project snapshot is good enough to construct New Chat's
  /// draft immediately. The server refresh that follows may update this
  /// list, but it must not hold the sheet behind a loading surface.
  /// Keep the initial choice on the selected machine, and only a project
  /// the user has used there before: with nothing remembered the draft
  /// starts with no project rather than guessing one.
  var draftProjectCandidate: Project? {
    guard let remembered = environment.composerDefaults.lastProjectId(forServer: resolvedServerId)
    else { return nil }
    return environment.projectList.fleetActiveProjects.first {
      $0.serverId == resolvedServerId && $0.id == remembered && !$0.isScratch
    }
  }

  /// The workspace's project. `prepare()` caches it in state, but it also
  /// resolves synchronously from the already-loaded project list, so the
  /// first frame renders the pane instead of a spinner — arriving from a new
  /// chat's first send must show the chat, not a placeholder.
  var resolvedProject: Project? {
    project
      ?? resolvedWorkspace.flatMap { workspace in
        environment.projectList.projects.first {
          $0.serverId == workspace.serverId && $0.id == workspace.projectId
        }
      }
      ?? draftController?.project
      ?? rootSession.flatMap { session in
        environment.projectList.projects.first {
          $0.serverId == session.serverId && $0.id == session.projectId
        }
      }
  }

  /// The app-wide cached controller for a chat, if it already exists — no
  /// creation, so this is safe to call straight from the view body.
  private func cachedController(for chatId: UUID) -> SessionController? {
    guard let session = session(for: chatId) else { return nil }
    return ChatControllerCache.shared.existingController(
      sessionId: chatId,
      serverId: session.serverId
    )
  }

  /// The controller a chat pane shows. A draft's pane is served by the
  /// retained draft controller — the SAME controller the session adopts, so
  /// nothing about the view changes when the send lands.
  func chatController(for pane: PaneDescriptorState) -> SessionController? {
    guard let chatId = pane.chatSessionId ?? activeSessionId else { return draftController }
    if chatId == draftPlaceholderId { return draftController }
    if let controller = controllers[chatId] { return controller }
    if chatId == sessionId, let initialController { return initialController }
    return cachedController(for: chatId)
  }

  func title(for pane: PaneDescriptorState) -> String {
    switch pane.kind {
    case .chat:
      let title =
        (pane.chatSessionId ?? activeSessionId)
        .flatMap(session(for:))?.title ?? pane.name
      return title.isEmpty ? "New Chat" : title
    case .newTab:
      return "New Tab"
    case .browser:
      return BrowserPaneCache.shared.localTitle(paneId: pane.id) ?? pane.name
    case .terminal, .plugin, .document, .screenSharing:
      return pane.name
    }
  }

  var workspaceCwd: String {
    resolvedWorkspace?.rootDirectory
      ?? rootSession?.cwd
      ?? resolvedProject?.folderURL.path
      ?? ""
  }

  var body: some View {
    ZStack {
      ChatSurfaceBackground()
        .ignoresSafeArea()
      workspaceContent
        .frame(maxWidth: .infinity, maxHeight: .infinity)
    }
  }

  private var workspaceContent: some View {
    Group {
      if blocksServerContent {
        let machines = environment.machines
        let machine =
          machines.machine(for: resolvedServerId)
          ?? machines.allMachines.first
          ?? CodevisorMachine.local
        ServerAvailabilityView(
          machineId: machine.id,
          availability: screenAvailability,
          machineName: machine.name,
          isLocal: false
        ) {
          Task {
            await machines.retryMachine(machine.id)
          }
        }
      } else if missing {
        ContentUnavailableView("Chat Not Found", systemImage: "questionmark.bubble")
      } else if isDraft, draftController == nil {
        // Once created, the retained draft controller owns its project.
        // Do not fall back to setup if an older global snapshot briefly
        // omits that project while its server upsert is acknowledged.
        // setUpDraftIfNeeded() runs synchronously at the start of
        // prepare() — with no project anywhere it still mints the
        // sentinel draft, so the composer always renders. Keep the
        // sheet calm for that initial actor turn.
        Color.clear
      } else if resolvedProject == nil {
        DelayedWorkspaceLoadingView()
      } else if preferredChatSessionId != nil || preferredPaneId != nil, paneState == nil {
        // An agent-row tap is an explicit route. Do not paint the
        // workspace's previously selected terminal/chat while the
        // destination task applies the requested pane.
        DelayedWorkspaceLoadingView()
      } else if homeLayoutMode == .split, let pane = activePane {
        // Regular width: the pane fills the workspace (under the top bar,
        // down to the bottom edge) and handles its own safe area.
        EdgeToEdgePaneHost { _, insets in
          paneContent(pane)
            .id(paneViewIdentities[pane.id] ?? pane.id)
            .safeAreaPadding(insets)
        }
      } else if let pane = activePane {
        paneContent(pane)
          .id(paneViewIdentities[pane.id] ?? pane.id)
      } else {
        DelayedWorkspaceLoadingView()
      }
    }
    // Native navigation back to the workspaces list: the system back
    // button and the edge swipe-to-go-back gesture. Hiding the back
    // button for a custom sidebar button disabled the interactive pop.
    // Beside a tiled sidebar the title repeats the selected row and costs
    // the transcript its height; it returns once the sidebar is collapsed
    // or floating, when nothing else names the screen.
    .navigationTitle(hidesTitleBesideSidebar ? "" : baseTitle)
    .navigationSubtitle(hidesTitleBesideSidebar ? "" : chatSubtitle)
    .navigationBarBackButtonHidden(isNewChatPresentation)
    .navigationBarTitleDisplayMode(.inline)
    // Sent chats and terminals align their title to the leading edge;
    // drafts keep a centered title.
    .toolbarRole(
      promotionNavigationTitle != nil || (!isDraft && [.chat, .terminal].contains(activePane?.kind))
        ? .editor : .automatic
    )
    .toolbar {
      if !blocksServerContent, let model = activeFileModel {
        FilePaneToolbar(model: model, onNewTab: { addTab() })
      } else {
        WorkspaceScreenToolbar(
          isNewChatPresentation: isNewChatPresentation,
          isPromotingNewChat: isPromotingNewChat,
          blocksServerContent: blocksServerContent,
          isDraft: isDraft,
          onDismissNewChat: { dismissNewChatPresentation() },
          onAddTab: { addTab() },
          showsBackMorph: !barsAreVertical
        )
      }
    }
    // The menu bar's tab commands act on this workspace.
    .focusedSceneValue(\.workspaceCommandActions, commandActions)
    .task(id: preparationIdentity) {
      IOSNavigationDiagnostics.record(
        "workspace.prepareTask",
        "availability=\(screenAvailability) route=\(String(describing: preparationIdentity.route)) draft=\(isDraft)"
      )
      guard isDraft || screenAvailability == .ready else { return }
      await prepare()
    }
    .onChange(of: activePane?.id) { old, new in
      IOSNavigationDiagnostics.record(
        "workspace.activePaneChanged",
        "old=\(old.map(Self.diagnosticID) ?? "nil") new=\(new.map(Self.diagnosticID) ?? "nil")"
      )
    }
    .onChange(of: environment.projectList.projects.map(\.id)) { _, _ in
      setUpDraftIfNeeded()
    }
    .onChange(of: environment.machines.allMachines.map(\.id)) { _, _ in
      setUpDraftIfNeeded()
      guard isDraft, let controller = draftController,
        let canonical = environment.machines.canonicalComposerMachineId(for: controller.project.serverId),
        canonical != controller.project.serverId
      else { return }
      let target =
        environment.projectList.projects.first {
          $0.serverId == canonical && $0.id == controller.project.id
        } ?? .runTargetPlaceholder(serverId: canonical)
      Task {
        await controller.retarget(to: target, serverClient: environment.machines.client(for: canonical))
      }
    }
    // A machine's harness catalog changed (sign-in, enablement, a
    // ferried credential landing): refresh a mounted draft composer so
    // new harnesses and models appear without reopening the screen.
    .onChange(of: environment.harnessCatalogRevision(for: resolvedServerId)) { _, _ in
      guard let draftController, isDraft else { return }
      draftController.invalidateHarnessCapabilities()
      Task { await draftController.refreshHarnessCapabilities() }
    }
    .onChange(of: environment.workspaceSync.revision) { _, _ in
      synchronizePaneStateFromWorkspace()
    }
    // The split layout re-targets this screen rather than mounting a new
    // one, so a sidebar tap arrives as a route change and must move the
    // selection in place — including when it names a chat instead of a pane.
    .onChange(of: preferredRoute) { _, _ in
      applyPreferredRoute()
    }
    // ...and the answer goes back, so the route never names a pane this
    // screen has since moved off and a later tap on that row still lands.
    .onChange(of: reportedPaneSelection) { _, selection in
      guard let selection else { return }
      onSelectedPaneChanged?(selection)
    }
    .iosNavigationDiagnostics(navigationDiagnosticState)
  }

  /// THIS screen's machine, not the app's selected one: a workspace can
  /// belong to any machine in the fleet (a chat sent to another machine's
  /// project), and the selected machine's hiccups must never block it —
  /// nor may its content wait on the wrong machine becoming ready.
  private struct PreparationIdentity: Equatable {
    let serverId: String
    let availability: ServerAvailability
    let route: MachineRoute?
  }

  private var preparationIdentity: PreparationIdentity {
    PreparationIdentity(
      serverId: resolvedServerId,
      availability: screenAvailability,
      route: environment.machines.statusByMachineId[resolvedServerId]?.route
    )
  }

  private var screenAvailability: ServerAvailability {
    environment.machines.availability(for: resolvedServerId)
  }

  var blocksServerContent: Bool {
    if isDraft { return false }
    // Machine preparation runs on every foreground. A cached chat remains
    // mounted, preserving its native surface, scroll position and composer.
    if let pane = activePane, pane.kind == .chat,
      let controller = chatController(for: pane), controller.model != nil
    {
      return false
    }
    if case .ready = screenAvailability {
      return false
    }
    return true
  }

  private var baseTitle: String {
    if let promotionNavigationTitle { return promotionNavigationTitle.title }
    if isDraft { return "New Chat" }
    guard let pane = activePane else { return "" }
    return title(for: pane)
  }

  private var chatSubtitle: String {
    if let promotionNavigationTitle { return promotionNavigationTitle.subtitle }
    guard !isDraft, activePane?.kind == .chat else { return "" }
    let projectName = resolvedProject.flatMap {
      $0.isScratch || $0.isRunTargetPlaceholder ? nil : $0.name
    }
    return [
      resolvedWorkspace?.name ?? projectName,
      environment.machines.fleetMachineName(for: resolvedServerId),
    ]
    .compactMap { $0 }
    .filter { !$0.isEmpty }
    .joined(separator: " · ")
  }
}
