import type { Context } from "hono"
import { html } from "hono/html"

import { isDevAuthEnabled, type CloudEnv } from "../env.js"
import { validAuthRedirect } from "./auth-navigation.js"

// Generated by `bun run build:css`; bundled as a text module (wrangler rules)
// and inlined so the Worker serves fully self-contained pages.
import styles from "../generated/styles.css"

type Ctx = Context<{ Bindings: CloudEnv }>

/// Cloud pages are server-rendered and framework-free. Machine/session
/// management lives in the native apps.

export const page = (c: Ctx, title: string, body: unknown, script?: string) =>
  c.html(
    html`<!doctype html>${(
        <html lang="en">
          <head>
            <meta charSet="utf-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <meta name="robots" content="noindex" />
            <meta name="referrer" content="no-referrer" />
            <title>{`${title} · ${c.env.INSTANCE_NAME}`}</title>
            <style dangerouslySetInnerHTML={{ __html: styles }} />
          </head>
          <body class="min-h-screen bg-zinc-950 font-sans text-zinc-100 antialiased">
            <main class="cloud-page">
              <section class="cloud-card">{body}</section>
            </main>
            {script !== undefined
              ? html`<script>
                  ${html([script] as unknown as TemplateStringsArray)}
                </script>`
              : null}
          </body>
        </html>
      )}`
  )

export const heading = (title: string, subtitle?: string) => (
  <div class="mb-6">
    <h1 class="text-xl font-semibold">{title}</h1>
    {subtitle !== undefined ? (
      <p class="mt-2 text-sm leading-relaxed text-zinc-400">{subtitle}</p>
    ) : null}
  </div>
)

// -- / ------------------------------------------------------------------------

export const homePage = (c: Ctx) =>
  page(
    c,
    "Cloud",
    <>
      {heading(
        "This is a Codevisor Cloud instance",
        "It connects your Codevisor apps to your machines through an end-to-end encrypted relay. There's nothing to do here — sign in from the Codevisor app, or run `codevisor auth login` on a machine."
      )}
      <a class="text-sm text-sky-400 hover:text-sky-300" href="https://codevisor.dev/docs">
        Codevisor documentation →
      </a>
    </>
  )

// -- /dev-login ---------------------------------------------------------------

export const devLoginPage = (c: Ctx) => {
  if (!isDevAuthEnabled(c.env)) return c.notFound()
  if (!validAuthRedirect(c.req.query("redirect") ?? "/")) {
    return c.json({ error: "invalid redirect" }, 400)
  }
  return page(
    c,
    "Dev sign in",
    <>
      {heading("Dev sign in", "Signing you in as the local development user…")}
      <p id="status" class="text-sm text-zinc-400">
        Working…
      </p>
    </>,
    `
    const redirect = new URLSearchParams(location.search).get("redirect") ?? "/";
    fetch("/dev/login", { method: "POST", credentials: "include" })
      .then((res) => {
        if (!res.ok) throw new Error("dev login failed");
        location.href = redirect;
      })
      .catch(() => { document.getElementById("status").textContent = "Dev login failed."; });
    `
  )
}

// -- /device ------------------------------------------------------------------

export const devicePage = (c: Ctx) =>
  page(
    c,
    "Connect a machine",
    <>
      {heading(
        "Connect a machine",
        "A machine running `codevisor auth login` showed you a code. Confirm it below to connect that machine to your account."
      )}
      <div id="signin" class="hidden">
        <p class="mb-4 text-sm text-zinc-400">You need to sign in first.</p>
        <a
          id="signin-link"
          class="block w-full rounded-lg bg-zinc-100 px-4 py-2.5 text-center text-sm font-medium text-zinc-900 hover:bg-white"
          href="/login"
        >
          Sign in to continue
        </a>
      </div>
      <form id="form" class="hidden flex-col gap-4">
        <input
          id="code"
          class="w-full rounded-lg border border-zinc-700 bg-zinc-950 px-4 py-3 text-center font-mono text-lg tracking-[0.3em] uppercase placeholder:tracking-normal placeholder:text-zinc-600"
          placeholder="Enter code"
          autocomplete="off"
          spellcheck={false}
        />
        <p class="text-xs leading-relaxed text-amber-400/90">
          Only approve codes you requested yourself, moments ago, on a machine you own. Anyone with
          an approved code can access your machines.
        </p>
        <div class="flex gap-3">
          <button
            id="approve"
            type="submit"
            class="flex-1 rounded-lg bg-emerald-500 px-4 py-2.5 text-sm font-semibold text-emerald-950 hover:bg-emerald-400"
          >
            Connect machine
          </button>
          <button
            id="deny"
            type="button"
            class="flex-1 rounded-lg border border-zinc-700 px-4 py-2.5 text-sm font-medium text-zinc-300 hover:bg-zinc-800"
          >
            Deny
          </button>
        </div>
      </form>
      <p id="result" class="hidden text-sm"></p>
    </>,
    `
    const qs = new URLSearchParams(location.search);
    const codeInput = document.getElementById("code");
    codeInput.value = qs.get("user_code") ?? "";
    const show = (id) => {
      for (const el of ["signin", "form", "result"]) document.getElementById(el).classList.add("hidden");
      const el = document.getElementById(id);
      el.classList.remove("hidden");
      if (id === "form") el.classList.add("flex");
    };
    const finish = (message, ok) => {
      const result = document.getElementById("result");
      result.textContent = message;
      result.className = "text-sm " + (ok ? "text-emerald-400" : "text-red-400");
      show("result");
    };
    fetch("/api/auth/get-session", { credentials: "include" })
      .then((res) => res.json())
      .then((session) => {
        if (!session || !session.user) {
          document.getElementById("signin-link").href =
            "/login?redirect=" + encodeURIComponent(location.pathname + location.search);
          show("signin");
        } else {
          show("form");
        }
      });
    const act = async (path) => {
      const userCode = codeInput.value.trim().replace(/-/g, "");
      if (!userCode) return;
      // Claim the code for this verifying session before acting on it.
      await fetch("/api/auth/device?user_code=" + encodeURIComponent(userCode), {
        credentials: "include"
      });
      const res = await fetch("/api/auth/device/" + path, {
        method: "POST",
        headers: { "content-type": "application/json" },
        credentials: "include",
        body: JSON.stringify({ userCode })
      });
      if (res.ok) {
        finish(path === "approve"
          ? "Machine connected. You can return to your terminal — it will finish up on its own."
          : "Request denied.", path === "approve");
      } else {
        const data = await res.json().catch(() => ({}));
        finish(data.message ?? "That code wasn't recognized. Codes expire after a few minutes.", false);
      }
    };
    document.getElementById("form").addEventListener("submit", (event) => { event.preventDefault(); act("approve"); });
    document.getElementById("deny").addEventListener("click", () => act("deny"));
    `
  )
