import { Schema } from "effect"

import { ClientContext, ClientNavigationRequest, ConnectedClient } from "./client-control.js"
import { ClientPageRequest, ClientLayoutRequest, ClientWindowRequest } from "./client-ui.js"
import {
  AgentSessionSummary,
  AnswerOpenCodeAuthRequest,
  AnswerPiAuthRequest,
  ApplyPluginUpdateRequest,
  BranchDiffTotals,
  CancelRequest,
  CloseWorkspacePaneResponse,
  CreateHarnessAccountRequest,
  CreateMcpServerRequest,
  CreateProjectFromGitRequest,
  CreateProjectRequest,
  CreateSessionRequest,
  CreateSkillRequest,
  CreateWorktreeRequest,
  CustomHarnessSpec,
  CustomHarnessTestResult,
  DetectMcpAuthRequest,
  DiscoverRemotePluginRequest,
  DiscoverRemotePluginResult,
  DiscoverRemoteSkillsRequest,
  DiscoverRemoteSkillsResult,
  DiscoveryInfo,
  EventCursorResponse,
  EventEnvelope,
  FileMetadata,
  FsListResponse,
  FsMkdirResponse,
  Harness,
  HarnessAccount,
  HarnessAuthFlow,
  AnswerHarnessAuthRequest,
  HarnessUsageLimits,
  HealthResponse,
  ImportNativeMcpsRequest,
  ImportNativeMcpsResult,
  ImportRemotePluginRequest,
  ImportRemoteSkillRequest,
  ImportSkillRequest,
  InvokePluginToolRequest,
  LinkPluginRequest,
  MakeSkillGlobalRequest,
  MarkSessionReadRequest,
  McpAuthDetection,
  McpOAuthStartResponse,
  McpServer,
  McpTool,
  NativeMcpRemoval,
  NativeMcpScan,
  OpenCodeAuthFlow,
  OpenCodeAuthProvider,
  OpenSessionRequest,
  OpenSessionResponse,
  PairingTokenResponse,
  PiAuthProvider,
  PiAuthProviderFlow,
  PluginListResponse,
  PluginPaneTokenRequest,
  PluginPaneTokenResponse,
  PluginRegistryIndex,
  PluginSummary,
  PluginUpdatePlan,
  PluginUpdatesResponse,
  Project,
  ProjectGitBranch,
  ProjectRecommendation,
  PromoteWorkspacePaneToChatRequest,
  PromoteWorkspacePaneToChatResponse,
  PromptAcceptedResponse,
  PromptQueueItem,
  PromptRequest,
  RemoveNativeMcpRequest,
  RemoveNativeMcpResult,
  ReorderQueuedPromptsRequest,
  RestartDrainRequest,
  RestartDrainState,
  ServerCapabilities,
  ServerInfo,
  SessionConfigOption,
  SessionDetail,
  SessionGoal,
  SessionSummary,
  SetConfigRequest,
  SetGoalRequest,
  SetModeRequest,
  SetNativeMcpEnabledRequest,
  SetPluginEnabledRequest,
  SetQuestionAnswerRequest,
  SetSkillInstalledRequest,
  SkillsScan,
  StartHarnessLoginRequest,
  StartOpenCodeAuthRequest,
  StartPiAuthRequest,
  SyncSkillsRequest,
  TailnetPeersResponse,
  TerminalCreateRequest,
  TerminalCreateResponse,
  TranscriptBodyPage,
  TranscriptItemDetails,
  TranscriptPage,
  UpdateHarnessAccountRequest,
  UpdateHarnessRequest,
  UpdateInfo,
  UpdateMcpServerRequest,
  UpdateProjectRequest,
  UpdateQueuedPromptRequest,
  UpdateSessionRequest,
  UpdateWorkspacePaneRequest,
  UpsertWorkspacePaneRequest,
  UpsertWorkspaceRequest,
  Workspace,
  WorkspacePane,
  WorkspaceSnapshot,
  Worktree
} from "./index.js"
import { MachineMcpState, SetMachineMcpEnabledRequest } from "./mcps.js"
import { NavigationSnapshot } from "./navigation.js"
import type { Endpoint } from "./openapi-endpoints.js"
import { PutSyncRequest, SyncDocument, SyncParticipation } from "./sync.js"

/// Request and response schemas per endpoint, rendered to JSON Schema for the
/// OpenAPI document.

export type JsonObject = Record<string, unknown>

export const jsonSchema = (schema: Schema.Constraint): JsonObject => {
  const document = Schema.toJsonSchemaDocument(schema, {
    additionalProperties: false,
    generateDescriptions: true
  })
  return { ...document.schema, $defs: document.definitions }
}

export const arrayOf = (schema: Schema.Constraint): Schema.Constraint => Schema.Array(schema)
export const nullable = (schema: Schema.Constraint): Schema.Constraint => Schema.NullOr(schema)

export const requestSchemas = (): Partial<Record<Endpoint, Schema.Constraint>> => ({
  "POST /v1/projects": CreateProjectRequest,
  "POST /v1/projects/from-git": CreateProjectFromGitRequest,
  "PATCH /v1/projects/:id": UpdateProjectRequest,
  "POST /v1/projects/:id/worktrees": CreateWorktreeRequest,
  "PUT /v1/workspaces/:id": UpsertWorkspaceRequest,
  "PUT /v1/workspaces/:workspaceId/panes/:paneId": UpsertWorkspacePaneRequest,
  "PATCH /v1/workspaces/:workspaceId/panes/:paneId": UpdateWorkspacePaneRequest,
  "POST /v1/workspaces/:workspaceId/panes/:paneId/promote-chat": PromoteWorkspacePaneToChatRequest,
  "PATCH /v1/harnesses/:id": UpdateHarnessRequest,
  "POST /v1/harnesses/:id/accounts": CreateHarnessAccountRequest,
  "PATCH /v1/harnesses/:id/accounts/:accountId": UpdateHarnessAccountRequest,
  "POST /v1/harnesses/:id/accounts/:accountId/login": StartHarnessLoginRequest,
  "POST /v1/harnesses/:id/accounts/:accountId/login/:flowId/answer": AnswerHarnessAuthRequest,
  "POST /v1/harnesses/pi/providers/:providerId/login": StartPiAuthRequest,
  "POST /v1/harnesses/pi/auth-flows/:flowId/answer": AnswerPiAuthRequest,
  "POST /v1/harnesses/opencode/accounts/:accountId/providers/:providerId/login":
    StartOpenCodeAuthRequest,
  "POST /v1/harnesses/opencode/auth-flows/:flowId/answer": AnswerOpenCodeAuthRequest,
  "PUT /v1/harnesses/custom": Schema.Struct({ harnesses: Schema.Array(CustomHarnessSpec) }),
  "POST /v1/harnesses/custom/test": CustomHarnessSpec,
  "POST /v1/plugins/discover-remote": DiscoverRemotePluginRequest,
  "POST /v1/plugins/import-remote": ImportRemotePluginRequest,
  "POST /v1/plugins/link": LinkPluginRequest,
  "POST /v1/plugins/:pluginId/panes/:paneId/token": PluginPaneTokenRequest,
  "POST /v1/plugins/:pluginId/tools/:toolName": InvokePluginToolRequest,
  "POST /v1/plugins/:pluginId/update/apply": ApplyPluginUpdateRequest,
  "PUT /v1/sync/:namespace": PutSyncRequest,
  "PUT /v1/sync-participation": SyncParticipation,
  "POST /v1/plugins/:pluginId/set-enabled": SetPluginEnabledRequest,
  "POST /v1/clients/:clientId/navigate": ClientNavigationRequest,
  "POST /v1/clients/:clientId/page": ClientPageRequest,
  "POST /v1/clients/:clientId/layout": ClientLayoutRequest,
  "POST /v1/clients/:clientId/window": ClientWindowRequest,
  "PUT /v1/mcps/:id/machine-state": SetMachineMcpEnabledRequest,
  "POST /v1/mcps": CreateMcpServerRequest,
  "POST /v1/mcps/detect-auth": DetectMcpAuthRequest,
  "PATCH /v1/mcps/:id": UpdateMcpServerRequest,
  "PATCH /v1/projects/:id/mcps/:mcpId": UpdateMcpServerRequest,
  "PATCH /v1/sessions/:id/mcps/:mcpId": UpdateMcpServerRequest,
  "POST /v1/native-mcps/import": ImportNativeMcpsRequest,
  "POST /v1/native-mcps/remove": RemoveNativeMcpRequest,
  "POST /v1/native-mcps/set-enabled": SetNativeMcpEnabledRequest,
  "POST /v1/skills": CreateSkillRequest,
  "POST /v1/skills/import": ImportSkillRequest,
  "POST /v1/skills/import-remote": ImportRemoteSkillRequest,
  "POST /v1/skills/discover-remote": DiscoverRemoteSkillsRequest,
  "POST /v1/skills/make-global": MakeSkillGlobalRequest,
  "POST /v1/skills/sync": SyncSkillsRequest,
  "PUT /v1/skills/:name/harnesses/:harnessId": SetSkillInstalledRequest,
  "POST /v1/sessions": CreateSessionRequest,
  "POST /v1/sessions/:id/open": OpenSessionRequest,
  "PATCH /v1/sessions/:id": UpdateSessionRequest,
  "POST /v1/sessions/:id/read": MarkSessionReadRequest,
  "PATCH /v1/sessions/:id/queue": ReorderQueuedPromptsRequest,
  "PATCH /v1/sessions/:id/queue/:queueId": UpdateQueuedPromptRequest,
  "POST /v1/sessions/:id/prompt": PromptRequest,
  "POST /v1/sessions/:id/cancel": CancelRequest,
  "POST /v1/sessions/:id/mode": SetModeRequest,
  "POST /v1/sessions/:id/config": SetConfigRequest,
  "POST /v1/sessions/:id/goal": SetGoalRequest,
  "POST /v1/sessions/:id/questions/:questionId/answer": SetQuestionAnswerRequest,
  "POST /v1/terminals": TerminalCreateRequest,
  "POST /v1/restart/drain": RestartDrainRequest
})

export const responseSchemas = (): Partial<Record<Endpoint, Schema.Constraint>> => ({
  "GET /v1/health": HealthResponse,
  "GET /v1/discovery": DiscoveryInfo,
  "GET /v1/info": ServerInfo,
  "GET /v1/tailnet/peers": TailnetPeersResponse,
  "GET /v1/update": UpdateInfo,
  "GET /v1/restart/drain": RestartDrainState,
  "POST /v1/restart/drain": RestartDrainState,
  "DELETE /v1/restart/drain": RestartDrainState,
  "GET /v1/sync/:namespace": SyncDocument,
  "PUT /v1/sync/:namespace": SyncDocument,
  "GET /v1/sync-participation": SyncParticipation,
  "PUT /v1/sync-participation": SyncParticipation,
  "GET /v1/capabilities": ServerCapabilities,
  "POST /v1/auth/pairing-token": PairingTokenResponse,
  "GET /v1/auth/connection-token": PairingTokenResponse,
  "POST /v1/auth/connection-token/rotate": PairingTokenResponse,
  "GET /v1/projects": arrayOf(Project),
  "GET /v1/projects/recommendations": arrayOf(ProjectRecommendation),
  "POST /v1/projects": Project,
  "POST /v1/projects/from-git": Project,
  "GET /v1/fs/list": FsListResponse,
  "POST /v1/fs/mkdir": FsMkdirResponse,
  "PATCH /v1/projects/:id": Project,
  "GET /v1/projects/:id/git/branches": arrayOf(ProjectGitBranch),
  "GET /v1/projects/:id/worktrees": arrayOf(Worktree),
  "POST /v1/projects/:id/worktrees": Worktree,
  "GET /v1/workspaces": arrayOf(Workspace),
  "GET /v1/workspace-snapshot": WorkspaceSnapshot,
  "GET /v1/workspace-panes": arrayOf(WorkspacePane),
  "PUT /v1/workspaces/:id": Workspace,
  "PUT /v1/workspaces/:workspaceId/panes/:paneId": WorkspacePane,
  "PATCH /v1/workspaces/:workspaceId/panes/:paneId": WorkspacePane,
  "POST /v1/workspaces/:workspaceId/panes/:paneId/promote-chat": PromoteWorkspacePaneToChatResponse,
  "POST /v1/workspaces/:workspaceId/panes/:paneId/close": CloseWorkspacePaneResponse,
  "DELETE /v1/workspaces/:workspaceId/panes/:paneId": CloseWorkspacePaneResponse,
  "GET /v1/harnesses": arrayOf(Harness),
  "POST /v1/harnesses/rescan": arrayOf(Harness),
  "POST /v1/harnesses/auth/refresh": arrayOf(Harness),
  "GET /v1/harnesses/pi/providers": arrayOf(PiAuthProvider),
  "POST /v1/harnesses/pi/providers/:providerId/login": PiAuthProviderFlow,
  "GET /v1/harnesses/pi/auth-flows/:flowId": PiAuthProviderFlow,
  "POST /v1/harnesses/pi/auth-flows/:flowId/answer": PiAuthProviderFlow,
  "GET /v1/harnesses/opencode/accounts/:accountId/providers": arrayOf(OpenCodeAuthProvider),
  "POST /v1/harnesses/opencode/accounts/:accountId/providers/:providerId/login": OpenCodeAuthFlow,
  "GET /v1/harnesses/opencode/auth-flows/:flowId": OpenCodeAuthFlow,
  "POST /v1/harnesses/opencode/auth-flows/:flowId/answer": OpenCodeAuthFlow,
  "GET /v1/harnesses/:id/agent-sessions": arrayOf(AgentSessionSummary),
  "PATCH /v1/harnesses/:id": Harness,
  "GET /v1/harnesses/:id/accounts": arrayOf(HarnessAccount),
  "POST /v1/harnesses/:id/accounts": HarnessAccount,
  "PATCH /v1/harnesses/:id/accounts/:accountId": HarnessAccount,
  "POST /v1/harnesses/:id/accounts/:accountId/activate": arrayOf(HarnessAccount),
  "POST /v1/harnesses/:id/accounts/:accountId/auth/probe": HarnessAccount,
  "POST /v1/harnesses/:id/accounts/:accountId/login": HarnessAuthFlow,
  "POST /v1/harnesses/:id/accounts/:accountId/login/:flowId/answer": HarnessAuthFlow,
  "POST /v1/harnesses/:id/accounts/:accountId/logout": HarnessAccount,
  "GET /v1/harnesses/custom": Schema.Struct({ harnesses: Schema.Array(CustomHarnessSpec) }),
  "PUT /v1/harnesses/custom": arrayOf(Harness),
  "POST /v1/harnesses/custom/test": CustomHarnessTestResult,
  "GET /v1/plugins": PluginListResponse,
  "GET /v1/plugins/registry": PluginRegistryIndex,
  "GET /v1/plugins/updates": PluginUpdatesResponse,
  "POST /v1/plugins/discover-remote": DiscoverRemotePluginResult,
  "POST /v1/plugins/import-remote": PluginSummary,
  "POST /v1/plugins/link": PluginSummary,
  "GET /v1/plugins/:pluginId": PluginSummary,
  "DELETE /v1/plugins/:pluginId": PluginListResponse,
  "POST /v1/plugins/:pluginId/restart": PluginSummary,
  "POST /v1/plugins/:pluginId/restore": PluginSummary,
  "POST /v1/plugins/:pluginId/set-enabled": PluginSummary,
  "POST /v1/plugins/:pluginId/update/prepare": PluginUpdatePlan,
  "POST /v1/plugins/:pluginId/update/apply": PluginSummary,
  "POST /v1/plugins/:pluginId/panes/:paneId/token": PluginPaneTokenResponse,
  // The tool's own response body — opaque JSON, shaped by each plugin.
  "POST /v1/plugins/:pluginId/tools/:toolName": Schema.Unknown,
  "GET /v1/clients": arrayOf(ConnectedClient),
  "GET /v1/clients/:clientId/context": ClientContext,
  "POST /v1/clients/:clientId/navigate": ClientContext,
  "POST /v1/clients/:clientId/page": ClientContext,
  "POST /v1/clients/:clientId/layout": ClientContext,
  "POST /v1/clients/:clientId/window": ClientContext,
  "GET /v1/mcps/:id/machine-state": MachineMcpState,
  "PUT /v1/mcps/:id/machine-state": MachineMcpState,
  "GET /v1/mcps": arrayOf(McpServer),
  "POST /v1/mcps": McpServer,
  "POST /v1/mcps/detect-auth": McpAuthDetection,
  "GET /v1/mcps/:id/tools": arrayOf(McpTool),
  "POST /v1/mcps/:id/connect": McpServer,
  "POST /v1/mcps/:id/oauth-start": McpOAuthStartResponse,
  "POST /v1/mcps/:id/oauth-disconnect": McpServer,
  "PATCH /v1/mcps/:id": McpServer,
  "PATCH /v1/projects/:id/mcps/:mcpId": arrayOf(McpServer),
  "PATCH /v1/sessions/:id/mcps/:mcpId": arrayOf(McpServer),
  "GET /v1/native-mcps": NativeMcpScan,
  "POST /v1/native-mcps/import": ImportNativeMcpsResult,
  "POST /v1/native-mcps/remove": RemoveNativeMcpResult,
  "GET /v1/native-mcps/removals": arrayOf(NativeMcpRemoval),
  "POST /v1/native-mcps/removals/:id/restore": NativeMcpScan,
  "POST /v1/native-mcps/set-enabled": NativeMcpScan,
  "GET /v1/skills": SkillsScan,
  "POST /v1/skills": SkillsScan,
  "POST /v1/skills/import": SkillsScan,
  "POST /v1/skills/import-remote": SkillsScan,
  "POST /v1/skills/discover-remote": DiscoverRemoteSkillsResult,
  "POST /v1/skills/make-global": SkillsScan,
  "POST /v1/skills/sync": SkillsScan,
  "PUT /v1/skills/:name/harnesses/:harnessId": SkillsScan,
  "DELETE /v1/skills/:name": SkillsScan,
  "GET /v1/navigation": NavigationSnapshot,
  "GET /v1/sessions": arrayOf(SessionSummary),
  "POST /v1/sessions": SessionSummary,
  "GET /v1/sessions/:id": SessionDetail,
  "GET /v1/sessions/:id/usage-limits": HarnessUsageLimits,
  "GET /v1/sessions/:id/branch-diff": nullable(BranchDiffTotals),
  "PATCH /v1/sessions/:id": SessionSummary,
  "POST /v1/sessions/:id/read": SessionSummary,
  "POST /v1/sessions/:id/unread": SessionSummary,
  "POST /v1/sessions/:id/connect": Schema.Struct({ agentSessionId: Schema.String }),
  "POST /v1/sessions/:id/open": OpenSessionResponse,
  "GET /v1/sessions/:id/transcript": TranscriptPage,
  "GET /v1/sessions/:id/transcript/:itemId/details": TranscriptItemDetails,
  "GET /v1/sessions/:id/transcript/:itemId/body": TranscriptBodyPage,
  "GET /v1/sessions/:id/queue": arrayOf(PromptQueueItem),
  "PATCH /v1/sessions/:id/queue": arrayOf(PromptQueueItem),
  "PATCH /v1/sessions/:id/queue/:queueId": PromptQueueItem,
  "POST /v1/sessions/:id/prompt": PromptAcceptedResponse,
  "POST /v1/sessions/:id/cancel": Schema.Struct({ cancelled: Schema.Boolean }),
  "POST /v1/sessions/:id/mode": Schema.Struct({ modeId: Schema.String }),
  "POST /v1/sessions/:id/config": Schema.Struct({
    configId: Schema.String,
    configOptions: Schema.optional(Schema.Array(SessionConfigOption))
  }),
  "POST /v1/sessions/:id/goal": SessionGoal,
  "POST /v1/sessions/:id/questions/:questionId/answer": Schema.Struct({
    outcome: Schema.Literals(["answered", "cancelled"]),
    questionId: Schema.String
  }),
  "POST /v1/files": FileMetadata,
  "GET /v1/events": EventEnvelope,
  "GET /v1/events/cursor": EventCursorResponse,
  "POST /v1/terminals": TerminalCreateResponse,
  "DELETE /v1/terminals/session/:sessionId": Schema.Struct({ closed: Schema.Boolean })
})
