/// Every HTTP/WebSocket endpoint the server exposes, plus the per-endpoint
/// metadata (summaries, success statuses) the OpenAPI builder reads.

export const endpoints = [
  "GET /v1/clients",
  "GET /v1/clients/:clientId/context",
  "POST /v1/clients/:clientId/navigate",
  "POST /v1/clients/:clientId/page",
  "POST /v1/clients/:clientId/layout",
  "POST /v1/clients/:clientId/window",
  "GET /v1/clients/:clientId/socket",
  "GET /v1/mcps/:id/machine-state",
  "PUT /v1/mcps/:id/machine-state",
  "POST /v1/harnesses/:id/accounts/:accountId/login/:flowId/answer",
  "GET /v1/health",
  "GET /v1/discovery",
  "GET /v1/info",
  "GET /v1/tailnet/peers",
  "GET /v1/openapi.json",
  "GET /v1/update",
  "POST /v1/update/apply",
  "GET /v1/restart/drain",
  "POST /v1/restart/drain",
  "DELETE /v1/restart/drain",
  "GET /v1/sync/:namespace",
  "PUT /v1/sync/:namespace",
  "GET /v1/sync/blobs/:id",
  "PUT /v1/sync/blobs/:id",
  "POST /v1/sync/skills/reconcile",
  "POST /v1/sync/mcps/reconcile",
  "POST /v1/sync/harnesses/reconcile",
  "POST /v1/sync/plugins/reconcile",
  "POST /v1/sync/accounts/publish",
  "GET /v1/sync-participation",
  "PUT /v1/sync-participation",
  "POST /v1/shutdown",
  "GET /v1/capabilities",
  "POST /v1/auth/pairing-token",
  "GET /v1/auth/connection-token",
  "POST /v1/auth/connection-token/rotate",
  "GET /v1/projects",
  "GET /v1/projects/recommendations",
  "POST /v1/projects",
  "POST /v1/projects/from-git",
  "POST /v1/projects/scratch",
  "PATCH /v1/projects/:id",
  "DELETE /v1/projects/:id",
  "GET /v1/projects/:id/git/branches",
  "GET /v1/projects/:id/worktrees",
  "POST /v1/projects/:id/worktrees",
  "GET /v1/workspaces",
  "GET /v1/workspace-snapshot",
  "GET /v1/workspace-panes",
  "PUT /v1/workspaces/:id",
  "DELETE /v1/workspaces/:id",
  "PUT /v1/workspaces/:workspaceId/panes/:paneId",
  "PATCH /v1/workspaces/:workspaceId/panes/:paneId",
  "POST /v1/workspaces/:workspaceId/panes/:paneId/promote-chat",
  "POST /v1/workspaces/:workspaceId/panes/:paneId/close",
  "DELETE /v1/workspaces/:workspaceId/panes/:paneId",
  "GET /v1/harnesses",
  "POST /v1/harnesses/rescan",
  "POST /v1/harnesses/auth/refresh",
  "GET /v1/harnesses/pi/providers",
  "POST /v1/harnesses/pi/providers/:providerId/login",
  "DELETE /v1/harnesses/pi/providers/:providerId",
  "GET /v1/harnesses/pi/auth-flows/:flowId",
  "POST /v1/harnesses/pi/auth-flows/:flowId/answer",
  "DELETE /v1/harnesses/pi/auth-flows/:flowId",
  "GET /v1/harnesses/opencode/accounts/:accountId/providers",
  "POST /v1/harnesses/opencode/accounts/:accountId/providers/:providerId/login",
  "DELETE /v1/harnesses/opencode/accounts/:accountId/providers/:providerId",
  "GET /v1/harnesses/opencode/auth-flows/:flowId",
  "POST /v1/harnesses/opencode/auth-flows/:flowId/answer",
  "DELETE /v1/harnesses/opencode/auth-flows/:flowId",
  "GET /v1/harnesses/:id/agent-sessions",
  "PATCH /v1/harnesses/:id",
  "GET /v1/harnesses/:id/accounts",
  "POST /v1/harnesses/:id/accounts",
  "PATCH /v1/harnesses/:id/accounts/:accountId",
  "DELETE /v1/harnesses/:id/accounts/:accountId",
  "POST /v1/harnesses/:id/accounts/:accountId/activate",
  "POST /v1/harnesses/:id/accounts/:accountId/auth/probe",
  "POST /v1/harnesses/:id/accounts/:accountId/login",
  "DELETE /v1/harnesses/:id/accounts/:accountId/login/:flowId",
  "POST /v1/harnesses/:id/accounts/:accountId/logout",
  "GET /v1/harnesses/custom",
  "PUT /v1/harnesses/custom",
  "POST /v1/harnesses/custom/test",
  "GET /v1/plugins",
  "GET /v1/plugins/registry",
  "GET /v1/plugins/updates",
  "POST /v1/plugins/discover-remote",
  "POST /v1/plugins/import-remote",
  "POST /v1/plugins/link",
  "GET /v1/plugins/:pluginId",
  "DELETE /v1/plugins/:pluginId",
  "POST /v1/plugins/:pluginId/restart",
  "POST /v1/plugins/:pluginId/restore",
  "POST /v1/plugins/:pluginId/set-enabled",
  "POST /v1/plugins/:pluginId/update/prepare",
  "POST /v1/plugins/:pluginId/update/apply",
  "GET /v1/plugins/:pluginId/icon",
  "GET /v1/plugins/:pluginId/panes/:paneType/icon",
  "POST /v1/plugins/:pluginId/panes/:paneId/token",
  "POST /v1/plugins/:pluginId/tools/:toolName",
  "GET /v1/mcps",
  "POST /v1/mcps",
  "POST /v1/mcps/detect-auth",
  "GET /v1/mcps/:id/tools",
  "POST /v1/mcps/:id/connect",
  "POST /v1/mcps/:id/oauth-start",
  "POST /v1/mcps/:id/oauth-disconnect",
  "PATCH /v1/mcps/:id",
  "DELETE /v1/mcps/:id",
  "PATCH /v1/projects/:id/mcps/:mcpId",
  "PATCH /v1/sessions/:id/mcps/:mcpId",
  "GET /v1/native-mcps",
  "POST /v1/native-mcps/import",
  "POST /v1/native-mcps/remove",
  "GET /v1/native-mcps/removals",
  "POST /v1/native-mcps/removals/:id/restore",
  "POST /v1/native-mcps/set-enabled",
  "GET /v1/skills",
  "POST /v1/skills",
  "POST /v1/skills/import",
  "POST /v1/skills/import-remote",
  "POST /v1/skills/discover-remote",
  "POST /v1/skills/make-global",
  "POST /v1/skills/sync",
  "PUT /v1/skills/:name/harnesses/:harnessId",
  "DELETE /v1/skills/:name",
  "GET /v1/navigation",
  "GET /v1/sessions",
  "POST /v1/sessions",
  "GET /v1/sessions/:id",
  "GET /v1/sessions/:id/usage-limits",
  "GET /v1/sessions/:id/branch-diff",
  "PATCH /v1/sessions/:id",
  "POST /v1/sessions/:id/read",
  "POST /v1/sessions/:id/unread",
  "DELETE /v1/sessions/:id/plan-approval",
  "DELETE /v1/sessions/:id",
  "POST /v1/sessions/:id/connect",
  "POST /v1/sessions/:id/open",
  "GET /v1/sessions/:id/transcript",
  "GET /v1/sessions/:id/transcript/:itemId/details",
  "GET /v1/sessions/:id/transcript/:itemId/body",
  "GET /v1/sessions/:id/events/socket",
  "GET /v1/sessions/:id/queue",
  "PATCH /v1/sessions/:id/queue",
  "PATCH /v1/sessions/:id/queue/:queueId",
  "DELETE /v1/sessions/:id/queue/:queueId",
  "POST /v1/sessions/:id/prompt",
  "POST /v1/sessions/:id/cancel",
  "POST /v1/sessions/:id/mode",
  "POST /v1/sessions/:id/config",
  "POST /v1/sessions/:id/goal",
  "DELETE /v1/sessions/:id/goal",
  "POST /v1/sessions/:id/questions/:questionId/answer",
  "POST /v1/files",
  "GET /v1/files/:id",
  "HEAD /v1/files/:id",
  "GET /v1/fs/list",
  "POST /v1/fs/mkdir",
  "GET /v1/events",
  "GET /v1/events/cursor",
  "GET /v1/events/socket",
  "POST /v1/terminals",
  "DELETE /v1/terminals/session/:sessionId",
  "GET /v1/terminals/:id/socket"
] as const

export type Endpoint = (typeof endpoints)[number]

export const summaries: Partial<Record<Endpoint, string>> = {
  "GET /v1/health": "Check server health",
  "GET /v1/discovery": "Get the tokenless discovery manifest",
  "GET /v1/info": "Get server information",
  "GET /v1/tailnet/peers": "List the machine's tailnet peers (for client-side discovery)",
  "GET /v1/openapi.json": "Get the OpenAPI document",
  "GET /v1/restart/drain": "Get the restart drain state (live turns the server is waiting on)",
  "POST /v1/restart/drain": "Begin draining live turns so the server can restart safely",
  "DELETE /v1/restart/drain": "Cancel a restart drain and dispatch held prompts",
  "POST /v1/auth/pairing-token": "Issue a pairing token",
  "GET /v1/auth/connection-token": "Get the machine's stable connection token",
  "POST /v1/auth/connection-token/rotate": "Rotate the machine's connection token",
  "GET /v1/events": "Stream global events with SSE",
  "GET /v1/events/cursor": "Get the durable global event cursor",
  "GET /v1/events/socket": "Open the global event WebSocket",
  "GET /v1/sessions/:id/events/socket": "Open a session event WebSocket",
  "GET /v1/terminals/:id/socket": "Attach to a terminal WebSocket"
}

export const noContent = new Set<Endpoint>([
  "DELETE /v1/projects/:id",
  "DELETE /v1/workspaces/:id",
  "DELETE /v1/harnesses/:id/accounts/:accountId",
  "DELETE /v1/harnesses/:id/accounts/:accountId/login/:flowId",
  "DELETE /v1/mcps/:id",
  "DELETE /v1/sessions/:id",
  "DELETE /v1/sessions/:id/plan-approval",
  "DELETE /v1/sessions/:id/queue/:queueId",
  "DELETE /v1/sessions/:id/goal"
])

export const created = new Set<Endpoint>([
  "POST /v1/auth/pairing-token",
  "POST /v1/auth/connection-token/rotate",
  "POST /v1/projects",
  "POST /v1/projects/:id/worktrees",
  "POST /v1/harnesses/:id/accounts",
  "POST /v1/harnesses/:id/accounts/:accountId/login",
  "POST /v1/plugins/import-remote",
  "POST /v1/plugins/link",
  "POST /v1/plugins/:pluginId/panes/:paneId/token",
  "POST /v1/mcps",
  "POST /v1/mcps/:id/oauth-start",
  "POST /v1/skills",
  "POST /v1/skills/import",
  "POST /v1/skills/import-remote",
  "POST /v1/sessions",
  "POST /v1/files",
  "POST /v1/terminals"
])

export const accepted = new Set<Endpoint>([
  "POST /v1/update/apply",
  "POST /v1/restart/drain",
  "POST /v1/shutdown",
  "POST /v1/sessions/:id/prompt",
  "POST /v1/sessions/:id/cancel",
  "POST /v1/sessions/:id/mode",
  "POST /v1/sessions/:id/config",
  "POST /v1/sessions/:id/goal",
  "POST /v1/sessions/:id/questions/:questionId/answer"
])

export const websocketEndpoints = new Set<Endpoint>([
  "GET /v1/clients/:clientId/socket",
  "GET /v1/events/socket",
  "GET /v1/sessions/:id/events/socket",
  "GET /v1/terminals/:id/socket"
])
