import Foundation
import Testing
import CodevisorClient
import CodevisorProtocol
@testable import CodevisorCloud

@Suite("CloudChannelCrypto")
struct CloudChannelCryptoTests {
  // Test vector generated by the TypeScript implementation
  // (packages/cloud-crypto) — the two must stay byte-for-byte compatible.
  private static let openerSecret = "AQIDBAUGBwgJCgsMDQ4PEBESExQVFhcYGRobHB0eHyA"
  private static let openerPublic = "B6N8vBQgk8i3VdwbEOhstCY3StFqqFPtC9_AsrhtHHw"
  private static let responderSecret = "ZWZnaGlqa2xtbm9wcXJzdHV2d3h5ent8fX5_gIGCg4Q"
  private static let responderPublic = "VxR2nRFr92Q2rnS8eT0sMK0ZA8WaxSc4BcfiaYtBDDY"
  private static let ephemeralSecret = "ycrLzM3Oz9DR0tPU1dbX2Nna29zd3t_g4eLj5OXm5-g"
  private static let ephemeralPublic = "TCn0mWmF6A0kfoC3AwOCRZL_n7rXSQTqfD0r2iTlHBI"
  private static let vectorChannelId = "vector-ch"
  private static let vectorSeq: UInt64 = 7
  private static let vectorPlaintext = "hello vector"
  private static let vectorBox = "LKHxh-IFUX1K6Ay_G198V94TOcLaDyDWq_IeCQ"

  private func decode(_ base64URL: String) throws -> Data {
    try #require(CloudChannelCrypto.base64URLDecode(base64URL))
  }

  @Test("Reproduces the TS vector box byte-for-byte")
  func openerVector() throws {
    let opened = try CloudChannelCrypto.openChannel(
      openerSecretKey: try decode(Self.openerSecret),
      responderPublicKey: Self.responderPublic,
      ephemeralSecretKey: try decode(Self.ephemeralSecret)
    )
    #expect(opened.ephemeralPublicKey == Self.ephemeralPublic)
    let box = try opened.cipher.seal(
      Data(Self.vectorPlaintext.utf8),
      channelId: Self.vectorChannelId,
      direction: .openerToResponder,
      seq: Self.vectorSeq
    )
    #expect(box == (try decode(Self.vectorBox)))
    #expect(try CloudChannelCrypto.publicKey(forSecretKey: decode(Self.openerSecret)) == Self.openerPublic)
  }

  @Test("Responder-side derivation decrypts the vector box")
  func responderVector() throws {
    let cipher = try CloudChannelCrypto.acceptChannel(
      responderSecretKey: try decode(Self.responderSecret),
      openerPublicKey: Self.openerPublic,
      ephemeralPublicKey: Self.ephemeralPublic
    )
    let plaintext = try cipher.open(
      try decode(Self.vectorBox),
      channelId: Self.vectorChannelId,
      direction: .openerToResponder,
      seq: Self.vectorSeq
    )
    #expect(String(decoding: plaintext, as: UTF8.self) == Self.vectorPlaintext)
  }

  @Test("Round-trips frames in both directions with fresh keys")
  func roundTrip() throws {
    let app = CloudChannelCrypto.generateKeyPair()
    let machine = CloudChannelCrypto.generateKeyPair()
    let opened = try CloudChannelCrypto.openChannel(
      openerSecretKey: app.secretKey,
      responderPublicKey: machine.publicKey
    )
    let responder = try CloudChannelCrypto.acceptChannel(
      responderSecretKey: machine.secretKey,
      openerPublicKey: app.publicKey,
      ephemeralPublicKey: opened.ephemeralPublicKey
    )

    let request = Data("resize 120x40".utf8)
    let sealedRequest = try opened.cipher.seal(
      request, channelId: "ch-1", direction: .openerToResponder, seq: 0
    )
    #expect(
      try responder.open(
        sealedRequest, channelId: "ch-1", direction: .openerToResponder, seq: 0
      ) == request)

    let reply = Data([1, 2, 3, 255])
    let sealedReply = try responder.seal(
      reply, channelId: "ch-1", direction: .responderToOpener, seq: 0
    )
    #expect(
      try opened.cipher.open(
        sealedReply, channelId: "ch-1", direction: .responderToOpener, seq: 0
      ) == reply)
  }

  @Test("Binds ciphertext to channel, direction, and seq")
  func aadBinding() throws {
    let app = CloudChannelCrypto.generateKeyPair()
    let machine = CloudChannelCrypto.generateKeyPair()
    let opened = try CloudChannelCrypto.openChannel(
      openerSecretKey: app.secretKey,
      responderPublicKey: machine.publicKey
    )
    let responder = try CloudChannelCrypto.acceptChannel(
      responderSecretKey: machine.secretKey,
      openerPublicKey: app.publicKey,
      ephemeralPublicKey: opened.ephemeralPublicKey
    )
    let sealed = try opened.cipher.seal(
      Data([7]), channelId: "ch-1", direction: .openerToResponder, seq: 4
    )
    #expect(throws: CloudChannelCryptoError.openFailed) {
      _ = try responder.open(sealed, channelId: "ch-2", direction: .openerToResponder, seq: 4)
    }
    #expect(throws: CloudChannelCryptoError.openFailed) {
      _ = try responder.open(sealed, channelId: "ch-1", direction: .responderToOpener, seq: 4)
    }
    #expect(throws: CloudChannelCryptoError.openFailed) {
      _ = try responder.open(sealed, channelId: "ch-1", direction: .openerToResponder, seq: 5)
    }
    #expect(
      try responder.open(
        sealed, channelId: "ch-1", direction: .openerToResponder, seq: 4
      ) == Data([7]))
  }

  @Test("Authenticates the opener's static key (dual DH)")
  func openerAuthentication() throws {
    let app = CloudChannelCrypto.generateKeyPair()
    let machine = CloudChannelCrypto.generateKeyPair()
    let impostor = CloudChannelCrypto.generateKeyPair()
    let opened = try CloudChannelCrypto.openChannel(
      openerSecretKey: app.secretKey,
      responderPublicKey: machine.publicKey
    )
    // Machine believes the peer is `impostor`, but frames were sealed
    // with the real app's static key — decryption must fail.
    let responder = try CloudChannelCrypto.acceptChannel(
      responderSecretKey: machine.secretKey,
      openerPublicKey: impostor.publicKey,
      ephemeralPublicKey: opened.ephemeralPublicKey
    )
    let sealed = try opened.cipher.seal(
      Data([1]), channelId: "ch-1", direction: .openerToResponder, seq: 0
    )
    #expect(throws: CloudChannelCryptoError.openFailed) {
      _ = try responder.open(sealed, channelId: "ch-1", direction: .openerToResponder, seq: 0)
    }
  }

  @Test("Fresh ephemerals derive distinct keys per channel open")
  func distinctKeysPerOpen() throws {
    let app = CloudChannelCrypto.generateKeyPair()
    let machine = CloudChannelCrypto.generateKeyPair()
    let first = try CloudChannelCrypto.openChannel(
      openerSecretKey: app.secretKey, responderPublicKey: machine.publicKey
    )
    let second = try CloudChannelCrypto.openChannel(
      openerSecretKey: app.secretKey, responderPublicKey: machine.publicKey
    )
    #expect(first.ephemeralPublicKey != second.ephemeralPublicKey)
    let sealed = try first.cipher.seal(
      Data([1]), channelId: "ch-1", direction: .openerToResponder, seq: 0
    )
    #expect(throws: CloudChannelCryptoError.openFailed) {
      _ = try second.cipher.open(sealed, channelId: "ch-1", direction: .openerToResponder, seq: 0)
    }
  }

  @Test("base64url round-trips every padding case, unpadded")
  func base64URL() throws {
    for length in [0, 1, 2, 3, 4, 31, 32, 33] {
      let bytes = Data((0..<length).map { UInt8(($0 * 37) % 256) })
      let encoded = CloudChannelCrypto.base64URLEncode(bytes)
      #expect(!encoded.contains("+") && !encoded.contains("/") && !encoded.contains("="))
      #expect(CloudChannelCrypto.base64URLDecode(encoded) == bytes)
    }
    #expect(CloudChannelCrypto.base64URLDecode("not valid!") == nil)
  }

  @Test("Rejects malformed boxes")
  func malformedBox() throws {
    let app = CloudChannelCrypto.generateKeyPair()
    let machine = CloudChannelCrypto.generateKeyPair()
    let opened = try CloudChannelCrypto.openChannel(
      openerSecretKey: app.secretKey, responderPublicKey: machine.publicKey
    )
    #expect(throws: CloudChannelCryptoError.invalidBox) {
      _ = try opened.cipher.open(
        Data(count: 4),
        channelId: "ch-1",
        direction: .responderToOpener,
        seq: 0
      )
    }
  }
}
